Add new `raw` command to get the raw contents of a message
PaleoCrafter/harmony pull request #46
Opened 2021-11-18 22:37 UTC by LewsTherinTelescope

2021-11-18 22:38 UTC, LewsTherinTelescope commented
metadata I used:
```
{name: 'raw', description: 'Get the raw contents of a message', options: [{ name: 'message', description: 'Link to a message', required: true, type: 3  }] }
```

2021-11-21 16:53 UTC, PaleoCrafter requested changes
Code itself looks good, just some minor stylistic things

2021-11-21 16:53 UTC, PaleoCrafter commented on src/raw-message.ts
> +			if (match) {
To reduce the amount of nesting in the code, I'd prefer if the "happy" path was the least-indented one. So turn this `if` into a negative test and pull the `else`` contents up here with an early return.

2021-11-21 16:53 UTC, PaleoCrafter commented on src/raw-message.ts
> +				else {
I've now enabled the `brace-style` eslint rule on master, so this is no longer valid :sweat_smile:

2021-11-22 07:55 UTC, PaleoCrafter approved these changes

2021-11-22 09:35 UTC, merged